---
title: "IFNy_Metadata"
author: "Harsha Tamtam"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
#this chuck is to setup defaults for basic settings of the webpage, note that this chunk is R language and the chunk below is CSS language
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

the chunk of code below formats the code on the webpage
```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

### Library Section
```{r Libraries}
library(tidyverse)
library(dplyr)
library(tibble)
library(scales)
library(edgeR)
```


### Viewing Data
```{r include=FALSE}

# this command creates an object (remove hashtag to make the function below operational)
# my_data <- data.frame(x = 1:5, y = letters[1:5])

# this commands write file into the disk drive (remove hashtag to make the function below operational)
# saveRDS(metadata, "data/metadata_IFNy.RDS")
# saveRDS(counts, "data/counts_IFNy.RDS")

# these commands load the files above into a different name (the object name)
metadata <- readRDS("data/metadata_IFNy.RDS")
counts <- readRDS("data/counts_IFNy.RDS")
```



```{r eval=FALSE, include=FALSE}
head(metadata)
```


```{r eval=FALSE, include=FALSE}
metadata$Condition
length(metadata$Condition) ### number of rows
str(metadata)  

dim(metadata)
mean(metadata$Mapped_Reads)
metadata %>% 
  summary()
```

```{r Averaged mapped reads by Individual in Species box plot}

ggplot(metadata, aes(x=Species,y=Mapped_Reads))+
  geom_boxplot(aes(fill=Species))+
  geom_point(data = metadata, aes(x = Species, y = Mapped_Reads))+
  labs(title = "Average Mapped RNA_Sequencing Reads between Species",y="Mean Counts")+
  theme_bw()+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```

```{r Average mapped read counts between each individual, column plot}

metadata %>% 
  group_by(Individual) %>% 
  summarise(avgMapped_Reads=mean(Mapped_Reads)) %>% 
ggplot(., aes(x=Individual, y=avgMapped_Reads))+
  geom_col(aes(fill=Individual))+
  geom_point()+
  labs(title = "Mapped RNA_Sequencing reads between individuals",y="Mapped read count", x="Individual" )+
  theme_bw()+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```

```{r Assigning Ensemble_IDs to row names}

# The function below reassigns the original row names (i.e: 1, 2 ,3, etc.) to their respective Ensembl_ID column and deletes the Entrez_ID and Symbol columns
Ensembl_ID_rownames <- counts %>%
  column_to_rownames(var = "Ensemble") %>% 
  select(-c(Entrez_ID, Symbol))
```

```{r Making Boxplot showing distributions of gene counts}

# The functions below manipulate the reorganized data frame from above to make a box plot showing the RNA count distributions for each sample
Ensembl_ID_rownames %>% 
  rownames_to_column("genes") %>% 
  pivot_longer(-genes, names_to = "Samples", values_to = "count_distributions") %>% 
  mutate(count_distributions = as.numeric(count_distributions)) %>% 
  
ggplot(., aes(x= Samples, y=count_distributions))+
    geom_boxplot()+
    labs(title = "Individual Count Distributions",y="RNA Count Distributions")+
    theme_bw()+
    theme(plot.title = element_text(size = rel(2), hjust = 0.5),
          axis.title = element_text(size = 15, color = "black"),
          axis.ticks = element_line(linewidth = 1.5),
          axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
          axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
          strip.text.y = element_text(color = "white"))
  
```


```{r A Boxplot of Continuous Count values}

better_genecount_boxplot <- Ensembl_ID_rownames %>% 
  rownames_to_column("genes") %>% 
  pivot_longer(-genes, names_to = "Samples", values_to = "count_distributions") %>% 
  mutate(count_distributions = as.numeric(count_distributions)) %>% 
  left_join(metadata, by = c("Samples" = "SampleName"))
# the "+ 1" after y variable counts_distribution shown below is to include zero values where log10(0) = undefined
ggplot(better_genecount_boxplot, aes(x = Condition, y = count_distributions + 1)) +
  geom_boxplot()+
  scale_y_log10()+
  labs(title = "Individual Count Distributions",y="RNA Count Distributions")+
  theme_bw()+
  theme(plot.title = element_text(size = rel(2), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))
```

```{r Converting the Continuous Counts values to Log2 CPM values}

count_matrix <- Ensembl_ID_rownames %>%
  mutate(across(everything(), as.numeric)) %>%
  as.matrix() #This function makes sure the counts table, labeled Ensembl_ID_rownames, is converted to a matrix

log2_cpm <- cpm(count_matrix, log = TRUE, prior.count = 1) #This function assigns the log2_cpm function with the calculation to convert counts to log2 cpm

log2_cpm_tbl <- log2_cpm %>% #We are now converting this log2_cpm function data matrix back to a data frame under the tibble library
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  as_tibble()

```


```{r A Boxplot of Log2 CPM values}

better_log2cpm_boxplot <- log2_cpm_tbl %>% 
  pivot_longer(-genes, names_to = "Samples", values_to = "log2cpm_values") %>% 
  mutate(log2cpm_values = as.numeric(log2cpm_values)) %>% 
  left_join(metadata, by = c("Samples" = "SampleName"))

ggplot(better_log2cpm_boxplot, aes(x = Condition, y = log2cpm_values)) +
  geom_boxplot() +
  labs(title = "Log2 CPM Values",y="Log2 CPM Distributions")+
  theme_bw()+
  theme(plot.title = element_text(size = rel(2), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```


```{r All samples Log2CPM distributions put in histogram}
log2_cpm_tibble <- log2_cpm %>%
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  as_tibble()

log2_cpm_histogram <- log2_cpm_tibble %>%
  pivot_longer(-genes, names_to = "Samples", values_to = "log2cpm")

ggplot(log2_cpm_histogram, aes(x = log2cpm)) +
  geom_histogram(bins = 50) +
  labs(title = "Distribution of log2 CPM Values", x = "log2 CPM", y = "Frequency") +
  theme_bw() +
  theme(plot.title = element_text(size = rel(2), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```

```{r All samples in histogram distinguished by color, eval=FALSE, include=FALSE}

ggplot(log2_cpm_histogram,
       aes(x = log2cpm,
           fill = Samples)) +
  geom_histogram(
    bins = 50,
    alpha = 0.4,
    position = "identity"
  ) +
  theme_bw() +
  theme(plot.title = element_text(size = rel(2), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```

```{r Separating the histogram of log2 cpm values per unique sample}

ggplot(log2_cpm_histogram,
       aes(x = log2cpm)) +
  geom_histogram(bins = 50) +
  facet_wrap(~Samples) +
  theme_bw() +
  theme(plot.title = element_text(size = rel(2), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.text.y = element_text(size =10, color = "black", angle = 0, hjust = 0.8, vjust = 0.5),
        axis.text.x = element_text(size =10, color = "black", angle = 90, hjust = 1, vjust = 0.2),
        strip.text.y = element_text(color = "white"))

```

```{r Filtering out lowly expressed genes where log2cpm is less than zero}

gene_means <- rowMeans(log2_cpm)
  filtered_log2_cpm <- log2_cpm[gene_means > 0, ]
  # this code output the number of rows, i.e: the number of genes where log2 > 0
  #nrow(filtered_log2_cpm)
  # this code outputs the difference between rows of the df log2_cpm, unfiltered from the rows of the df filtered_log2_cpm, which is the number of genes that were removed from filtering, as in the number of genes removed where log2 cpm < 0
  #nrow(log2_cpm) - nrow(filtered_log2_cpm)

# Before filtering
  before_tbl <- log2_cpm %>%
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  pivot_longer(-genes, names_to = "Samples", values_to = "log2cpm") %>%
  mutate(Filter = "Before")

# After filtering
  after_tbl <- filtered_log2_cpm %>%
  as.data.frame() %>%
  rownames_to_column("genes") %>%
  pivot_longer(-genes, names_to = "Samples", values_to = "log2cpm") %>%
  mutate(Filter = "After")

# This combines the before and after tables to visualize the original and filtered cpm frequency values 
combined_tbl <- bind_rows(before_tbl, after_tbl)

# This code creates a histogram cpm distribution **before filtering**
ggplot(before_tbl, aes(x = log2cpm, fill = )) +
  geom_histogram(bins = 50, alpha = 0.3, position = ("identity")) +
  theme_bw() +
  labs(title = "Log2 CPM Distributions", x = "log2 CPM", y = "Frequencies before filtering")

# This code creates a histogram cpm distribution **after filtering**
ggplot(after_tbl, aes(x = log2cpm, fill = )) +
  geom_histogram(bins = 50, alpha = 0.3, position = ("identity")) +
  theme_bw() +
  labs(title = "Log2 CPM Distributions", x = "log2 CPM", y = "Frequencies after filtering")

# This code creates a histogram cpm distribution data before and after filtering
ggplot(combined_tbl, aes(x = log2cpm, fill = Filter)) +
  geom_histogram(bins = 50, alpha = 0.3, position = ("identity")) +
  theme_bw() +
  labs(title = "Log2 CPM Distributions", x = "log2 CPM", y = "Frequency")

# This code creates box plots cpm distribution data before and after filtering
reordered_combined_tbl <- combined_tbl %>%
  mutate(Filter = factor(Filter, levels = c("Before", "After"))) 

ggplot(reordered_combined_tbl, aes(x = Filter, y = log2cpm, fill = Filter)) +
  geom_boxplot(outlier.shape = NA) +
  theme_bw() +
  labs(title = "Log2 CPM Boxplots",y = "log2 CPM")
```


